services:
  - type: web
    name: rwe-mobile-app
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build:web
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
