services:
  - type: web
    name: rwe-mobile-app
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm install -g serve && npx expo export:web
    startCommand: serve web-build -l $PORT -s
    envVars:
      - key: NODE_ENV
        value: production
