services:
  - type: web
    name: rwe-mobile-app
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npx expo export --platform web --output-dir web-build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
